/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"fmt"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/intstr"
	"k8s.io/utils/ptr"

	rpcv1alpha1 "github.com/insidegreen/rpc-operator-claude/api/v1alpha1"
)

// projectLabelKey marks pods/resources as belonging to a named PipelineProject.
const projectLabelKey = "rpc.operator.io/project"

// natsImageDefault is the pinned default NATS server image used when the
// Helm chart override (features.projects.nats.image+tag) is unset.
const natsImageDefault = "nats:2.10-alpine"

// natsClientPort is the standard NATS client port.
const natsClientPort = 4222

// natsClusterPort is the inter-NATS-replica routing port (used when replicas > 1).
const natsClusterPort = 6222

// natsMonitorPort is the NATS monitoring HTTP port (/healthz, /jsz).
const natsMonitorPort = 8222

// natsStorageDefault is the per-replica JetStream PVC size when unset.
var natsStorageDefault = resource.MustParse("10Gi")

// natsConfigFile is the file name written into the NATS ConfigMap.
const natsConfigFile = "nats-server.conf"

// projectChildClusterName returns the canonical name of the managed PipelineCluster.
func projectChildClusterName(projectName string) string {
	return projectName + "-cluster"
}

// projectChildNATSName returns the canonical name of the managed NATS resources
// (StatefulSet, headless Service, ConfigMap).
func projectChildNATSName(projectName string) string {
	return projectName + "-nats"
}

// buildProjectCluster returns the child PipelineCluster CR a Project owns.
// Namespace is intentionally unset; the reconciler keys the object before applying.
func buildProjectCluster(project *rpcv1alpha1.PipelineProject) *rpcv1alpha1.PipelineCluster {
	var instances int32 = 1
	var resources corev1.ResourceRequirements
	if project.Spec.Cluster != nil {
		if project.Spec.Cluster.Instances != nil {
			instances = *project.Spec.Cluster.Instances
		}
		if project.Spec.Cluster.Resources != nil {
			resources = *project.Spec.Cluster.Resources
		}
	}
	return &rpcv1alpha1.PipelineCluster{
		ObjectMeta: metav1.ObjectMeta{
			Name:   projectChildClusterName(project.Name),
			Labels: map[string]string{projectLabelKey: project.Name},
		},
		Spec: rpcv1alpha1.PipelineClusterSpec{
			Replicas:    instances,
			JSONLogging: true,
			Resources:   resources,
		},
	}
}

// natsServerConfig returns the JetStream-enabled NATS server config rendered
// for the given replica count. Single-replica configs omit cluster routes.
func natsServerConfig(projectName string, replicas int32) string {
	base := fmt.Sprintf(`# Generated by rpc-operator — do not edit by hand.
server_name: $POD_NAME
listen: 0.0.0.0:%d
http: 0.0.0.0:%d

jetstream {
  store_dir: "/data/jetstream"
}
`, natsClientPort, natsMonitorPort)

	if replicas <= 1 {
		return base
	}

	// Cluster routes resolve via the headless Service DNS:
	// <pod>.<svc>.<ns>.svc.cluster.local
	svc := projectChildNATSName(projectName)
	return base + fmt.Sprintf(`
cluster {
  name: %q
  listen: 0.0.0.0:%d
  routes = [
    nats-route://%s-0.%s:%d
    nats-route://%s-1.%s:%d
    nats-route://%s-2.%s:%d
  ]
}
`, projectName, natsClusterPort,
		svc, svc, natsClusterPort,
		svc, svc, natsClusterPort,
		svc, svc, natsClusterPort)
}

// buildProjectNATSConfigMap returns the ConfigMap holding the NATS server config.
func buildProjectNATSConfigMap(projectName string, replicas int32) *corev1.ConfigMap {
	return &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{
			Name:   projectChildNATSName(projectName),
			Labels: map[string]string{projectLabelKey: projectName},
		},
		Data: map[string]string{natsConfigFile: natsServerConfig(projectName, replicas)},
	}
}

// buildProjectNATSService returns a headless Service exposing the NATS pods
// for in-namespace consumption. ClusterIP=None for stable pod DNS used by
// JetStream peers and downstream Connect instances.
func buildProjectNATSService(projectName string) *corev1.Service {
	return &corev1.Service{
		ObjectMeta: metav1.ObjectMeta{
			Name:   projectChildNATSName(projectName),
			Labels: map[string]string{projectLabelKey: projectName},
		},
		Spec: corev1.ServiceSpec{
			ClusterIP: corev1.ClusterIPNone,
			Selector:  map[string]string{projectLabelKey: projectName, "rpc.operator.io/component": "nats"},
			Ports: []corev1.ServicePort{
				{Name: "client", Port: natsClientPort, TargetPort: intstr.FromInt(natsClientPort), Protocol: corev1.ProtocolTCP},
				{Name: "cluster", Port: natsClusterPort, TargetPort: intstr.FromInt(natsClusterPort), Protocol: corev1.ProtocolTCP},
				{Name: "monitor", Port: natsMonitorPort, TargetPort: intstr.FromInt(natsMonitorPort), Protocol: corev1.ProtocolTCP},
			},
		},
	}
}

// buildProjectNATSStatefulSet returns the NATS JetStream StatefulSet a Project owns.
// volumeClaimTemplates persist JetStream data; image is overridable via the
// Helm chart (features.projects.nats.image+tag → natsImage arg).
func buildProjectNATSStatefulSet(
	projectName, natsImage string,
	replicas int32,
	storage resource.Quantity,
) *appsv1.StatefulSet {
	if natsImage == "" {
		natsImage = natsImageDefault
	}
	if storage.IsZero() {
		storage = natsStorageDefault
	}

	labels := map[string]string{
		projectLabelKey:             projectName,
		"rpc.operator.io/component": "nats",
	}

	return &appsv1.StatefulSet{
		ObjectMeta: metav1.ObjectMeta{
			Name:   projectChildNATSName(projectName),
			Labels: map[string]string{projectLabelKey: projectName},
		},
		Spec: appsv1.StatefulSetSpec{
			Replicas:    ptr.To(replicas),
			ServiceName: projectChildNATSName(projectName),
			Selector:    &metav1.LabelSelector{MatchLabels: labels},
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{Labels: labels},
				Spec: corev1.PodSpec{
					TerminationGracePeriodSeconds: ptr.To[int64](30),
					SecurityContext: &corev1.PodSecurityContext{
						RunAsNonRoot: ptr.To(true),
						RunAsUser:    ptr.To[int64](1000),
						FSGroup:      ptr.To[int64](1000),
						SeccompProfile: &corev1.SeccompProfile{
							Type: corev1.SeccompProfileTypeRuntimeDefault,
						},
					},
					Containers: []corev1.Container{{
						Name:  "nats",
						Image: natsImage,
						Args: []string{
							"--config", "/etc/nats/" + natsConfigFile,
						},
						Env: []corev1.EnvVar{{
							Name: "POD_NAME",
							ValueFrom: &corev1.EnvVarSource{
								FieldRef: &corev1.ObjectFieldSelector{FieldPath: "metadata.name"},
							},
						}},
						Ports: []corev1.ContainerPort{
							{Name: "client", ContainerPort: natsClientPort, Protocol: corev1.ProtocolTCP},
							{Name: "cluster", ContainerPort: natsClusterPort, Protocol: corev1.ProtocolTCP},
							{Name: "monitor", ContainerPort: natsMonitorPort, Protocol: corev1.ProtocolTCP},
						},
						LivenessProbe: &corev1.Probe{
							ProbeHandler: corev1.ProbeHandler{HTTPGet: &corev1.HTTPGetAction{
								Path: "/healthz", Port: intstr.FromString("monitor"),
							}},
							InitialDelaySeconds: 10,
							PeriodSeconds:       10,
						},
						ReadinessProbe: &corev1.Probe{
							ProbeHandler: corev1.ProbeHandler{HTTPGet: &corev1.HTTPGetAction{
								Path: "/healthz?js-enabled-only=true", Port: intstr.FromString("monitor"),
							}},
							InitialDelaySeconds: 3,
							PeriodSeconds:       5,
						},
						SecurityContext: &corev1.SecurityContext{
							AllowPrivilegeEscalation: ptr.To(false),
							ReadOnlyRootFilesystem:   ptr.To(true),
							Capabilities: &corev1.Capabilities{
								Drop: []corev1.Capability{"ALL"},
							},
						},
						VolumeMounts: []corev1.VolumeMount{
							{Name: "config", MountPath: "/etc/nats", ReadOnly: true},
							{Name: "data", MountPath: "/data"},
						},
					}},
					Volumes: []corev1.Volume{{
						Name: "config",
						VolumeSource: corev1.VolumeSource{
							ConfigMap: &corev1.ConfigMapVolumeSource{
								LocalObjectReference: corev1.LocalObjectReference{
									Name: projectChildNATSName(projectName),
								},
								Items: []corev1.KeyToPath{{Key: natsConfigFile, Path: natsConfigFile}},
							},
						},
					}},
				},
			},
			VolumeClaimTemplates: []corev1.PersistentVolumeClaim{{
				ObjectMeta: metav1.ObjectMeta{Name: "data", Labels: labels},
				Spec: corev1.PersistentVolumeClaimSpec{
					AccessModes: []corev1.PersistentVolumeAccessMode{corev1.ReadWriteOnce},
					Resources: corev1.VolumeResourceRequirements{
						Requests: corev1.ResourceList{corev1.ResourceStorage: storage},
					},
				},
			}},
		},
	}
}
